server:
  port: 8084

spring:
  application:
    name: payment-service
  cloud:
    compatibility-verifier:
      enabled: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:paymentdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER:org.h2.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

app:
  rabbitmq:
    exchange: booking_exchange
    payment-queue: payment_queue
    booking-created-routing-key: booking.created
    payment-completed-routing-key: payment.completed
    booking-failed-routing-key: booking.failed
    dlq:
      exchange: booking_dlx
      queue: booking_events_dlq
      routing-key: booking.created.dlq
