version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8084:8084"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8086:8086"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
