spring.application.name=demo

# C?u hình ???ng d?n t?i khóa b?ng classpath
jwt.public.key=classpath:app.pub
jwt.private.key=classpath:app.key

spring.security.user.name=admin
spring.security.user.password=123456
spring.security.user.roles=ADMIN