server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        - id: movie-service
          uri: http://movie-service:8082
          predicates:
            - Path=/api/movies/**
          filters:
            - StripPrefix=1
        - id: booking-service
          uri: http://booking-service:8083
          predicates:
            - Path=/api/bookings/**
          filters:
            - StripPrefix=1
        - id: payment-service
          uri: http://payment-service:8084
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: http://notification-service:8086
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1
  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
