version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  node-app:
    build: .
    container_name: my_node_app
    ports:
      - "3000:3000"
    depends_on:
      - mysql